pipeline {
	agent any 

	stages {
		stage ("checkout project") {
			steps {
				echo "check project code from main repo"
				checkout scm
				echo "teoreticaly done"
			}
		}
		stage ("see docker compose version") {
			steps {
				echo "start"
				script {
					//sh 'docker-compose up -d --build'
					sh 'docker-compose --version'
				}
				echo "end"
			}
		}
		stage ("try build") {
			steps {
				script {
					sh 'docker-compose build'
				}
			}		
		}
		stage ("try up") {
			steps {
				script {
					sh 'docker-compose up -d'
				}
			}		
		}
		stage ("checkout test") {
			steps {
				echo "checkout test proj"
			}
		}
		stage ("run test") {
			steps {
				echo "run tests"
			}
		}
		stage('Stop Docker Compose') {
            steps {
                script {
                    sh 'docker-compose down'
                }
            }
        }
	}

	post {
        always {
            // Убедитесь, что Docker Compose остановлен
            sh 'docker-compose down'
        }
    }
}
